# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build - C5-Envelope

on:
  push:
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'dev'
    #  - 'prod'
    branches: [ main ]

  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}

    - name: Build JS Envelope
      run: |
        npm ci
        npm install
        npm run build
        npm run test
        npm pack

    - name: Build PYTHON Envelope
      run: |
        npm run generate-python
        python3 -m pip install --upgrade -r requirements.txt
        python3 -m src.simple_envelope_test
        python3 -m build

