# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release - C5-Envelope

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}

    - uses: mabels/neckless@main
      with:
        version: v0.1.7

    - name: Publish C5-Envelope NPM
      env:
        NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
      run: |
        rm -rf ./dist
        eval $(neckless kv ls --shKeyValue --ghAddMask NPM_PASS  NPM_USER "NPM_TOTP@Totp()")
        # env | sort | grep NPM
        token=$(curl -H "npm-otp: $NPM_TOTP" \
             -X PUT \
             -H 'content-type: application/json' \
             -d "{\"name\":\"$NPM_USER\", \"password\": \"$NPM_PASS\"}" \
             https://registry.npmjs.org/-/user/org.couchdb.user:$NPM_USER | jq -r .token)
        echo "//registry.npmjs.org/:_authToken=$token" > $HOME/.npmrc
        npm ci
        npm install
        npm run build
        npm run test
        npm publish --otp=$(neckless kv ls --onlyValue "NPM_TOTP@Totp()")

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Publish C5-Envelope PYTHON
      env:
        NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
      run: |
        rm -rf ./dist
        eval $(neckless kv  ls  --shKeyValue --ghAddMask TWINE_PASSWORD)
        npm run generate-python
        python3 --version
        python3 -m pip install --upgrade -r requirements.txt
        python3 -m src.simple_envelope_test
        python3 -m build
        python3 -m twine upload dist/* -u fastandfearless 

