# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release - C5-Envelope

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}

    - name: Build C5-Envelope
      run: |
        npm ci
        npm install
        npm run build
        npm run test

    - name: Fetch Neckless
      run: |
        curl -L -o ./neckless https://github.com/mabels/neckless/releases/download/v0.1.3/default.neckless-linux-amd64
        chmod 755 ./neckless
        ls -l
        ./neckless version

    - name: Publish C5-Envelope
      env:
        NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
      run: |
        eval $(./neckless kv  ls  --shKeyValue --ghAddMask NPM_PASS  NPM_USER "NPM_TOTP@Totp() TWINE_PASSWORD")
        # env | sort | grep NPM
        token=$(curl -H "npm-otp: $NPM_TOTP" \
             -X PUT \
             -H 'content-type: application/json' \
             -d "{\"name\":\"$NPM_USER\", \"password\": \"$NPM_PASS\"}" \
             https://registry.npmjs.org/-/user/org.couchdb.user:$NPM_USER | jq -r .token)
        echo "//registry.npmjs.org/:_authToken=$token" > $HOME/.npmrc
        npm publish --otp=$(./neckless kv ls --onlyValue "NPM_TOTP@Totp()")
        python3 -m build
        pip3 install twine
        python3 -m twine upload dist/* -u fastandfearless 

